### PR TITLE
Add support for core::option::Option<T>

### PR DESCRIPTION
**Pull request by mcuelenaere**
This PR adds support for core::option::Option<T>

### CODE REVIEW

**Comment by djkoloski** [comment]
Thanks for the PR! It looks like there's some code duplicated from rkyv for writing `ArchivedOption`. I'll see if I can expose some more convenient functions to reduce the duplication there. Otherwise this looks good.

**Comment by mcuelenaere** [comment]
Yeah I just quickly hacked this together to get my usecase working.

Now I would also like to intern the keys of a `HashMap` (which happen to overlap with another `Vec<String>`), but at this point it's becoming a copy-paste of the main rkyv crate.

**Comment by djkoloski** [comment]
Yeah nested types are a bit of a pain. It's possible that newtyping `String` would result in a better API surface, i.e.

```rust
#[repr(transparent)]
pub struct Interned<T>(T);

impl<T: Archive> Archive for Interned<T> { ... }

// etc.
```

This will pollute the original type, but it might be easier than pushing a wrapper through a bunch of containers. I still think that having an implementation for `Option` is a good idea and might experiment to see what it looks like with hashmaps and B-trees.

**Comment by djkoloski** [comment]
I took some time to think about the problem and break it down. I think the best option for container types is:

- In `resolve_with` and `serialize_with`, reinterpret cast `field` to a wrapped type (e.g. `Option<T>` casts to `Option<With<T, W>>`) and serialize/resolve as normal.
- In `deserialize_with`, deserialize to the internally-wrapped type (e.g. `Option<With<T, W>>`) and then unwrap that into the original type (e.g. `Option<T>`) however suitable. Ideally, this could just be a `transmute` of the wrapped type. However, that has some problems with generics so a more manual operation may be required.

I'm going to merge this for now. I think that getting some equivalent impls working for container types like `HashMap` and `BTreeMap` is a good next step, which we now have a playbook for. Then the only blockers for a proper release should be some tests.

**Pull request merged**
